server{
    lsiten 80;
    server_name adriangarza.dev ://adriangarza.dev;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html =404;
    }
}